---
- name: Remove existing deployment
  file: path="{{tomcat_home}}/webapps/sample" state=absent

- name: Install webapp
  copy: src="../files/sample.war" dest="{{tomcat_home}}/webapps"
 
- name: Start Tomcat
  command: "nohup {{tomcat_home}}/bin/startup.sh"
  
